source 'https://rubygems.org'

gem 'rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'pg', '~> 0.18.1'
gem 'activerecord-jdbcsqlite3-adapter',  platforms: [:jruby]
gem 'jquery-rails'
gem 'grape'
gem 'grape-entity'
gem 'uglifier'
gem 'zip-zip'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'rubocop'
  gem 'nokogiri'
end

# a super serious windows compatibility issue
gem 'tzinfo'
gem 'tzinfo-data'
